// SQLite Contants
export const CREATE_NEW_TABLE = 'CREATE TABLE IF NOT EXISTS'
export const PRIMARY_KEY_AUTOINCREMENT = 'PRIMARY KEY AUTOINCREMENT'
export const INSERT_INTO = 'INSERT INTO'
export const SELECT = 'SELECT'
export const FROM = 'FROM'
export const VALUES = 'VALUES'
export const UPDATE = 'UPDATE'
export const SET = 'SET'
export const WHERE = 'WHERE'
